name: Bug Report
description: Create a bug report to help us improve this mod
labels: [ "bug", "triage" ]
body:
  -   type: dropdown
      attributes:
        label: Minecraft Version
        description: The version of Minecraft you were using when the bug occured
        options:
          - "1.20.1"
          - "1.19.4"
          - "1.19.3"
          - "1.19.2"
      validations:
        required: true
  -   type: textarea
      attributes:
        label: Describe the Bug
        description: A clear and concise description of what the bug is
      validations:
        required: true
  -   type: markdown
      attributes:
        value: "Thank you for taking the time to make this bug report and help improve this mod!"