name: Incompatibility Report
description: Create a incompatibility report to help us improve this mod
labels: [ "mod interaction", "triage" ]
body:
  -   type: dropdown
      attributes:
        label: Minecraft Version
        description: The version of Minecraft you were using when the incompatibility occurred
        options:
          - "1.20.1"
          - "1.19.4"
          - "1.19.3"
          - "1.19.2"
      validations:
        required: true
  -   type: input
      attributes:
        label: What Mods Conflicts with
        description: Incompatible mod name
      validations:
        required: true
  -   type: textarea
      attributes:
        label: Describe the Incompatibility
        description: A clear and concise description of what happened. If applicable, add screenshots or videos to help explain your problem.
      validations:
        required: true
  -   type: markdown
      attributes:
        value: "Thank you for taking the time to make this incompatibility report and help improve this mod!"