name: Incompatibility Report
description: Create a incompatibility report to help us improve this mod
labels: [ "mod interaction", "triage" ]
body:
  -   type: input
      attributes:
        label: What Mods Conflicts with
        description: Incompatible mod name
      validations:
        required: true
  -   type: textarea
      attributes:
        label: Describe the Incompatibility
        description: A clear and concise description of what happened
      validations:
        required: true
  -   type: textarea
      attributes:
        label: Screenshots and Videos
        description: If applicable, add screenshots or videos to help explain your problem.
      validations:
        required: false
  -   type: input
      attributes:
        label: Crash Report or Log
        description: If applicable, please add a **link** to the crash report or log that was created when this issue occurred. You can upload the crash report to a site like Pastebin or GitHub Gist. Please **do not** paste the whole crash report in this issue.
      validations:
        required: false
  -   type: dropdown
      attributes:
        label: Mod Version
        description: The version of the mod you were using when the incompatibility occurred
        options:
          - "1.0.0"
          - "Older version"
      validations:
        required: true
  -   type: input
      attributes:
        label: Incompatible Mod Version
        description: The version of incompatible mod you were using when the incompatibility occurred
        placeholder: x.y.z
      validations:
        required: true
  -   type: dropdown
      attributes:
        label: Minecraft Version
        description: The version of Minecraft you were using when the incompatibility occurred
        options:
          - "1.19.3"
          - "1.19.2"
      validations:
        required: true
  -   type: input
      attributes:
        label: Forge Version
        description: The version of Forge you were using when the bug incompatibility occurred
        placeholder: 43.1.52
      validations:
        required: false
  -   type: textarea
      attributes:
        label: Other Mods
        description: Please list any other mods that were running when the incompatibility happened.
      validations:
        required: false
  -   type: textarea
      attributes:
        label: Additional Context
        description: Add any extra context about the incompatibility here
      validations:
        required: false
  -   type: markdown
      attributes:
        value: "Thank you for taking the time to make this incompatibility report and help improve this mod!"