name: Release
on: [workflow_dispatch]

permissions:
  contents: write

env:
  MINECRAFT_VERSION: 1.21.1
  JAVA_VERSION: 21
  VERSION: 1.1.0

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: "temurin"
          java-version: 17

      - name: Make Gradle Wrapper Executable
        if: ${{ runner.os != 'Windows' }}
        run: chmod +x ./gradlew

      - name: Build
        run: ./gradlew build

      - name: Publish (CurseForge/Modrinth)
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          # Modrinth
          modrinth-id: RZwVw5iA
          modrinth-featured: true
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}

          # CurseForge
          curseforge-id: 729120
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}

          # Config
          name: "Drink Beer Refill ${{ env.VERSION }} for ${{ env.MINECRAFT_VERSION }}"
          version: ${{ env.VERSION }}
          version-type: release
          changelog-file: changelog/${{ env.VERSION }}.md
          files: build/libs/*-${{ env.VERSION }}!(-@(dev|sources|slim)).jar

          loaders: |
            forge
          game-versions: |
            ${{ env.MINECRAFT_VERSION }}
          java: |
            ${{ env.JAVA_VERSION }}
          retry-attempts: 2
          retry-delay: 10000